apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndk-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ndk-lbl
    spec:
      containers:
      - name: ndk
        image: DOCKERHUB_USERNAME/YOUR_APP_NAME
        ports:
        - name: ndk-app-port
          containerPort: 3000
