apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-service-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-service-lbl
    spec:
      containers:
      - name: nodejs-service
        image: DOCKERHUB_USERNAME/YOUR_APP_NAME
        ports:
        - name: nodejs-service-app-port
          containerPort: 3000
