apiVersion: v1
kind: Pod
metadata:
  name: nodejs-service-app
  labels:
    app: nodejs-service-lbl
spec:
  containers:
  - name: nodejs-service
    image: DOCKERHUB_USERNAME/YOUR_APP_NAME
    ports:
    - name: nodejs-service-app-port
      containerPort: 3000
