apiVersion: v1
kind: Service
metadata:
  name: nginx-service-server
spec:
  ports:
  - port: 80
    # this target port is the deployment service port we expose to the Internet
    targetPort: nginx-port
    protocol: TCP
  # 'selector' means that this service is created for the pod that is labelled with the key/value pair 'app:label'
  selector:
    app: nginx-service
  type: LoadBalancer
